build up pipeline

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -49,9 +49,48 @@ jobs:
         username: ${{ secrets.GITLAB_USERNAME }}
         password: ${{ secrets.GITLAB_PASSWORD }}
 
-    - name: Build docker
-      if: matrix.os == 'ubuntu-latest'
+  generate_missing_images:
+    runs-on: ubuntu-latest
+
+    needs: build
+
+    steps:
+    - name: Checkout
+      run: |
+        git clone https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.com/wolfee/graphi-2022.git
+
+    - name: Install extra runtime
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
+
+    - name: Install conan
+      uses: turtlebrowser/get-conan@main
+
+    - name: Build latest
       run: |
         cd graphi-2022
+        cmake --build build --config Release --target install
         docker build -t registry.gitlab.com/wolfee/graphi-2022/game:latest -f dockers/game ./target
         docker image push registry.gitlab.com/wolfee/graphi-2022/game:latest
+
+    - name: Check tags
+      run: |
+        cd graphi-2022
+        git show-ref --tags | while read -r line ; do
+          HASH=`echo $line | cut -d ' ' -f1`
+          TAG=`echo $line | cut -d ' ' -f2`
+          TAG=`echo $TAG | cut -d '/' -f3`
+          echo "Checking tag $TAG..."
+          docker pull registry.gitlab.com/wolfee/graphi-2022/game:$TAG &> /dev/null
+          if [[ $? ]]; then
+              echo "$TAG not found, building from hash $HASH..."
+              rm -rf build
+              git checkout $HASH
+              cmake --build build --config Release --target install
+              docker build -t registry.gitlab.com/wolfee/graphi-2022/game:$TAG -f dockers/game ./target
+              docker image push registry.gitlab.com/wolfee/graphi-2022/game:$TAG
+          else
+              echo "$TAG found."
+          fi
+        done
